{% set name = "package_name" %}
{% set version = "0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 6791bd670efd086c99706c6dd82ba2d4dcee397a575c51f257398c8028f616be

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - package_name

about:
  home: "https://github.com/Rositaguipla/staged-recipes"
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "A Python package for test conda-forge"
  doc_url: "https://blog.gishub.org/how-to-publish-a-python-package-on-conda-forge"
  dev_url: "https://github.com/Rositaguipla/staged-recipes"

extra:
  recipe-maintainers:
    - Rositaguipla
